# UDTS Sąveikos Vadovas

Šioje repozitorijoje talpinama techninė dokumentacija, skirta duomenų teikėjams, norintiems dalyvauti UDTS ekosistemoje.

## Struktūra
Dokumentacija generuojama naudojant [Sphinx](https://www.sphinx-doc.org/) ir talpinama [ReadTheDocs](https://readthedocs.org/).

- \docs/source/\ - Dokumentacijos išeities tekstai (Markdown formatu).
- \docs/source/conf.py\ - Sphinx konfigūracija.

## Paleidimas lokaliai (Windows)

1. Įsidiekite priklausomybes:
   \\\powershell
   pip install -r requirements.txt
   \\\
2. Sugeneruokite HTML:
   \\\powershell
   sphinx-build -b html docs/source docs/build/html
   \\\
"@ | Out-File -Encoding UTF8 README.md

# 5. Sukuriame ReadTheDocs konfigūraciją
@"
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt

sphinx:
  configuration: docs/source/conf.py
